### ISSUE TITLE
SyntaxError: Use of const in strict mode. - NodeJS version update necessary

### ISSUE THREAD

**Issue by pm2002** [flapdoodle-oss/de.flapdoodle.embed.nodejs#1]
NodeJS modules, that use "const" won't work anymore. Previously working modules are failing after dependency updates, with the following error:
`[nodejs error] SyntaxError: Use of const in strict mode.`
Providing a more up to date nodejs version would solve this issue, according to: https://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode (answer by: Alexander). Is it alternatively possible to provide the `--harmony`-flag to the Flapdoodle Embedded Node.js?

**Comment by michaelmosmann** [comment]
Sure.. :)


Am 1. März 2018 09:20:57 schrieb pm2002 <notifications@github.com>:

**Comment by pm2002** [comment]
So, what are you referring to?
a) a nodejs version update or
b) the `--harmony`-flag?
Btw.: thanks for providing this solution! Hope to see an update soon!? :)

**Comment by michaelmosmann** [comment]
We can do both..
But it will take me some days..

Make a pull request,if you like:)

Michael:)


Am 4. März 2018 10:01:08 schrieb pm2002 <notifications@github.com>:

**Comment by pm2002** [comment]
Best choice would probably be the nodejs update, because it makes the flag (for most cases) superfluous. Looking forward to that! Btw.: you probably know your code better and hence know what to do. I would probably leave messy code and need multiplied X days longer ;) *thx* 4 your efforts!

**Comment by michaelmosmann** [comment]
I will try my best:)

Am 6. März 2018 21:01:07 schrieb pm2002 <notifications@github.com>:
Best choice would probably be the nodejs update, because it makes the flag 
(for most cases) superfluous. Looking forward to that! Btw.: you probably 
know your code better and hence know what to do. I would probably leave 
messy code and need multiplied X days longer ;) thx 4 your efforts!

**Comment by michaelmosmann** [comment]
@pm2002 hmm.. i think a fix for this is to late to help anyone.. i close this issue as i think nobody uses this project anymore.
